### ISSUE TITLE
Problems after the update

### ISSUE THREAD

**Issue by TAVAN021** [ChrisAnd1998/FalconX-Center-Taskbar#97]
New version crashed infinitely, Windows 10 v1909. Looks like it can only exist for one or two seconds. I just commented in Microsoft Store. I'm a Chinese user.

**Comment by Cabola** [comment]
I have the same issue with the latest version 1.3.3.0 it starts then crashes then starts then crashes for xx amount of time before finally just crashing totally.

**Comment by rohrmant** [comment]
Im also having same issue with infinite crashes on newest version

**Comment by ChrisAnd1998** [comment]
I can't reproduce the bug but, i hope it will be fixed next update due to some changes i made.

**Comment by rohrmant** [comment]
Appreciate it man. Let me know if you need any additional info like windows
build or anything. Was weird because it only started with the newest
version.

**Comment by ChrisAnd1998** [comment]
Can you see if it's fixed in this testing build?
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v1.zip

**Comment by Lisser** [comment]
> 
> 
> Can you see if it's fixed in this testing build?
> https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v1.zip

I had the same problem as OP, but this build seems to be working again!

**Comment by ChrisAnd1998** [comment]
Good to hear that 😁. I will wait for more confirmation until i mark it as a fix "for next update".

**Comment by rhalfkann** [comment]
Problem persists for me with 1.3.4.0_v1 on Win 10 1909 Build 18363.476

**Comment by ChrisAnd1998** [comment]
Did you get any error log? Or just none?

**Comment by rohrmant** [comment]
Will be home shortly to test

**Comment by Cabola** [comment]
It didn't fix it for me either, this time however it doesn't display the program a quick second as it did last time. Now it just launches, crashes, launches, crashes. I can see the icon down by the clock and sometimes it even displays the taskbar icon.

**Comment by rohrmant** [comment]
Im still having the same crash issues as well, I'm updating my windows now
to see if maybe that was causing the issue. Ill get back to you shortly,
thanks a ton for the responses man, active  developers deserve a couple
coffees bought for them

**Comment by ChrisAnd1998** [comment]
Thanks :) @rohrmant 

It would help a lot if someone is able to clip this behavior so i can hopefully see exactly whats going on.

I also have this output reader.
https://chrisandriessen.nl/web/downloads/falconx/Testing/FalconXOutput.exe
You need to put it in the folder where you installed FalconX. Then use the FalconXOutput.exe to run FalconX. Maybe it will show where it crashes as @Cabola explains.

**Comment by rohrmant** [comment]
Christ I'll run your output program for you and send a clip to you after
work.

**Comment by rohrmant** [comment]
So when I run the Output program it crashes the App and the output window,
I could be using the wrong terminology so let me clip it and show you whats
happening

**Comment by rohrmant** [comment]
https://ttprivatenew.s3.amazonaws.com/pulse/forfalconx/attachments/12069212/Forfalconx+support.mp4

**Comment by ChrisAnd1998** [comment]
Thanks making a clip of it. I really appreciate your help 😁😁.

It may sound simple but, do you have any anti virus software running atm? If yes try disabling it and then run FalconX. Or do you have any other application that modifies the taskbar/startmenu?

I will look into this further tomorrow.

**Comment by rohrmant** [comment]
I have my antivirus disabled. But I'll actually uninstall it and double
check all my running programs and see if I find a conflict.

**Comment by ChrisAnd1998** [comment]
I'll keep trying as i am coding blind here XD.

I have reverted some changes i made.
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v2.zip

**Comment by ChrisAnd1998** [comment]
And what about v5?
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v5.zip

**Comment by Cabola** [comment]
Neither worked for me, both halt after first initiation run output in the output.exe. Then hangs for a few secs, before crashing both output.exe & falconx.exe and then begin the loop start/crash.

**Comment by ChrisAnd1998** [comment]
Thats so weird :(. I reversed every change i made in 1.3.3.0 to what it was in 1.3.2.0

**Comment by ChrisAnd1998** [comment]
v7 will catch any error and will throw a message box.
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v7.zip

**Comment by Cabola** [comment]
I've tried running it with the output.exe and without the output.exe and haven't gotten any message box. The output.exe shows this in the first initiation run output, then hangs, crashes, starts the loop.

Could it be because I'm using 3 monitors?
![falconxcrash](https://user-images.githubusercontent.com/19853946/70392424-450bee80-19e0-11ea-8ca4-a9a426797363.png)

**Comment by rohrmant** [comment]
Thats the exact thing that mine shows and then starts the same crash
process as well. IDK that its a monitor issue because I was using it before
with 2 monitors just fine, havent changed my setup at all

**Comment by Cabola** [comment]
This is how it looks like in v.1.3.2.0 just as it starts the first loop in the output.exe
![falconxcrash](https://user-images.githubusercontent.com/19853946/70392522-4a1d6d80-19e1-11ea-94c6-74fdd77790b7.png)

**Comment by ChrisAnd1998** [comment]
Thanks for testing :)
Seems that it doesn't make it the the Animator.

I made some changes there.
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v7.zip

**Comment by Cabola** [comment]
that one works! And just for good measure here's the output.exe
![falconxcrash](https://user-images.githubusercontent.com/19853946/70392913-cc5b6100-19e4-11ea-8783-9fdc8ebdd0d4.png)

**Comment by ChrisAnd1998** [comment]
Finally!

**Comment by Cabola** [comment]
Nope that one doesn't work either, does the same thing, here's the output.exe:
![falconxcrash](https://user-images.githubusercontent.com/19853946/70392977-a3879b80-19e5-11ea-961f-6b1ce97c66a7.png)

**Comment by Cabola** [comment]
> 
> 
> Okay....
> I will go back to 1.3.2.0 if it still happens...

I posted premature before. When I went to extract the zip I had forgotten to kill the process of the falconx.exe so it wasn't overwritten. So I was launching the 1.3.2 version which is working. The above is 1.3.4.0_v8 which hangs right there then crashes and starts the loop..

**Comment by ChrisAnd1998** [comment]
Allright i'll go back to 1.3.2.0

This is 1.3.2.0 + Fixed taskbar appearing blue when using "transparant" Taskbar Style
https://chrisandriessen.nl/web/downloads/falconx/Testing/1.3.4.0_v9.zip

**Comment by Cabola** [comment]
Yup 1.3.4.0_v9 works and doesn't crash, here's the output.exe:
![falconxcrash](https://user-images.githubusercontent.com/19853946/70393089-04fc3a00-19e7-11ea-993e-39c266b04e60.png)

**Comment by ChrisAnd1998** [comment]
Allright, i'll quickly push this to the store and my website to make everyone happy again :)
Thanks a lot for testing it out, much appreciated!

**Comment by Cabola** [comment]
You're most welcome, and now go relax and enjoy the holidays as you were meant to be!

**Comment by rohrmant** [comment]
Thanks for all the help chris and testing carstensen appreciate yall.
